---
train:

    params:
        batch_size: 256
        epoch: 6
        lr: 0.1
        weight_decay: 0.0001
        decay: 0.5
        decay_step: 3
        warmup: 0
    
    save:
        metapath: "result"
        folder: eth
        model_name: vicsgaze
        step: 1

    data:
        image: "/root/autodl-tmp/eth/Image/Train"
        label: "/root/autodl-tmp/eth/Label/Train.label"
        header: True
        name: eth
        isFolder: False
    
    pretrain:
        enable: False
        path: "/root/autodl-tmp/byol/result/eth/checkpoint/Iter_2_trans6.pt"
        device: 0
    
    device: 0

    reader: reader
# dropout = 0
# dim_feed = 512
