---
train:

    params:
        batch_size: 256
        epoch: 40
        lr: 0.1
        weight_decay: 0.0001
        decay: 0.5
        decay_step: 20
        warmup: 5
    
    save:
        metapath: "result"
        folder: gaze360
        model_name: vicsgaze
        step: 10

    data:
        image: "/root/autodl-tmp/Gaze360-New/Image/all"
        label: "/root/autodl-tmp/Gaze360-New/Label/all"
        header: True
        name: gaze360
        isFolder: True
    
    device: 0

    reader: reader
# dropout = 0
# dim_feed = 512
