---
train:

    params:
        batch_size: 256
        epoch: 40
        lr: 0.1
        weight_decay: 0.0001
        decay: 0.5
        decay_step: 20
        warmup: 5
    
    params_linear:
        batch_size: 256
        epoch: 80
        lr: 0.0005
        decay: 0.5
        decay_step: 60
        warmup: 5

    save_linear:
        metapath: "result"
        folder: mpii
        model_name: linear
        step: 10
    
    save:
        metapath: "result"
        folder: mpii
        model_name: trans6
        step: 10

    data:
        image: "/root/autodl-tmp/MPIIFaceGaze-new/Image/"
        label: "/root/autodl-tmp/MPIIFaceGaze-new/Label/"
        header: True
        name: mpii
        isFolder: True
    
    device: 0

    reader: reader
# dropout = 0
# dim_feed = 512
